server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.15:3306/springSecurity?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 192.168.2.15
    port: 6379
    username:
    password:
# MyBatis配置
mybatis-plus:
  type-Aliases-Package: com.lsy.**.entity
  mapper-Locations: classpath*:mapper/**/*Mapper.xml
  config-Location: classpath:mybatis/mybatis-config.xml